//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessGame.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Bishop {
            get {
                return ResourceManager.GetString("Bishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid position!.
        /// </summary>
        internal static string Board_InvalidPosition {
            get {
                return ResourceManager.GetString("Board_InvalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already a piece at this position!.
        /// </summary>
        internal static string Board_TheresAPiece {
            get {
                return ResourceManager.GetString("Board_TheresAPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot put yourself in check!.
        /// </summary>
        internal static string ChessMatch_AutoCheck {
            get {
                return ResourceManager.GetString("ChessMatch_AutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destination..
        /// </summary>
        internal static string ChessMatch_InvalidDestination {
            get {
                return ResourceManager.GetString("ChessMatch_InvalidDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no piece at the chosen position..
        /// </summary>
        internal static string ChessMatch_NoPiece {
            get {
                return ResourceManager.GetString("ChessMatch_NoPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no possible moves to this piece..
        /// </summary>
        internal static string ChessMatch_NoPossibleMoves {
            get {
                return ResourceManager.GetString("ChessMatch_NoPossibleMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen piece is not yours..
        /// </summary>
        internal static string ChessMatch_NotYourPiece {
            get {
                return ResourceManager.GetString("ChessMatch_NotYourPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string Pawn {
            get {
                return ResourceManager.GetString("Pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Rook {
            get {
                return ResourceManager.GetString("Rook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Screen_Black {
            get {
                return ResourceManager.GetString("Screen_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black: .
        /// </summary>
        internal static string Screen_BlackCaptured {
            get {
                return ResourceManager.GetString("Screen_BlackCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured pieces:.
        /// </summary>
        internal static string Screen_CapturedPieces {
            get {
                return ResourceManager.GetString("Screen_CapturedPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK!.
        /// </summary>
        internal static string Screen_Check {
            get {
                return ResourceManager.GetString("Screen_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKMATE!.
        /// </summary>
        internal static string Screen_Checkmate {
            get {
                return ResourceManager.GetString("Screen_Checkmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   a b c d e f g h.
        /// </summary>
        internal static string Screen_Columns {
            get {
                return ResourceManager.GetString("Screen_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Destination: .
        /// </summary>
        internal static string Screen_Destination {
            get {
                return ResourceManager.GetString("Screen_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Origin: .
        /// </summary>
        internal static string Screen_Origin {
            get {
                return ResourceManager.GetString("Screen_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round: {0}.
        /// </summary>
        internal static string Screen_Round {
            get {
                return ResourceManager.GetString("Screen_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the player: {0}.
        /// </summary>
        internal static string Screen_WaitingPlayer {
            get {
                return ResourceManager.GetString("Screen_WaitingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Screen_White {
            get {
                return ResourceManager.GetString("Screen_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White: .
        /// </summary>
        internal static string Screen_WhiteCaptured {
            get {
                return ResourceManager.GetString("Screen_WhiteCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner: {0}.
        /// </summary>
        internal static string Screen_Winner {
            get {
                return ResourceManager.GetString("Screen_Winner", resourceCulture);
            }
        }
    }
}
